# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=2048)),
                ('city', models.CharField(default='New Delhi', max_length=64, verbose_name='city')),
                ('state', models.CharField(default='Delhi', max_length=68, verbose_name='state')),
                ('zipcode', models.CharField(default='110001', max_length=6, verbose_name='zip code')),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField(blank=True)),
                ('phone3', models.IntegerField(blank=True)),
                ('website', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
