# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-20 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinfo',
            name='category',
            field=models.CharField(choices=[('Apparels', 'Apparels'), ('Astro', 'Astro'), ('Grooming', 'Grooming'), ('Events', 'Events'), ('Transport', 'Transport'), ('Venue', 'Venue'), ('MusicBand', 'MusicBand'), ('Services', 'Services'), ('Agents', 'Agents')], default='Apparels', max_length=15),
        ),
    ]
