# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_auto_20160623_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinfo',
            name='avg_review',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='vendorinfo',
            name='business_name',
            field=models.CharField(default='Test', max_length=1024),
        ),
    ]
