# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-22 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_auto_20160623_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinfo',
            name='phone2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinfo',
            name='phone3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
