# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-24 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0008_auto_20160725_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
    ]
