# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-24 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0010_auto_20160725_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinfo',
            name='city',
            field=models.CharField(default='delhi', max_length=64, verbose_name='city'),
        ),
    ]
