# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-08-23 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='wishlist',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
