# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-08-29 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20160823_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='wishlist',
            field=models.CharField(max_length=10000),
        ),
    ]
